addpath('Deliverable_3_1\', "src", "tbxmanager\", ...
    "C:\Users\otcsi\Documents\School stuff\EPFL\MA1\Model predictive control\casadi-3.6.4-windows64-matlab2018b" ...
    , "Deliverable_3_2\", "Deliverable_4_1\", "Deliverable_5_1\", "Deliverable_5_2\", "Deliverable_6_1\", "Deliverable_6_2\")
startup